version: '3'
services:
  # aecl:
  #   build: 
  #     context: .
  #   hostname: node
  #   expose: [1905]
  #   environment:
  #     COMPILER_URL: https://compiler.aepps.com
  #     DATABASE_URL: postgres://aecl:aecl@database/contracts_library?sslmode=disable
  
  database:
    image: postgres
    restart: unless-stopped
    ports: 
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: aecl
      POSTGRES_USER: aecl
      POSTGRES_DB: contracts_library
    volumes: 
    - aecl_data:/var/lib/postgresql/data
  
  compiler:
    image: aeternity/aesophia_http:v2.1.0
    hostname: compiler
    ports: 
    - 3080:3080


volumes:
  aecl_data: